# TODO: Waiting on `cargo-msrv` and `cross` to support TOML v1.1.
#:tombi toml-version = "v1.0.0"

[package]
name = "katharsis"
version = "1.0.0-canary.30"
edition = "2024"
rust-version = "1.88.0"
description = "CLI tool for generating RSS feeds."
repository = "https://github.com/arghena/katharsis"
license = "MIT"
keywords = ["cli", "feed", "generator", "rss", "tool"]
categories = ["command-line-utilities"]
include = ["/LICENSE", "/src/"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }{ archive-suffix }"
bin-dir = "{ name }-v{ version }-{ target }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.'cfg(target_os = "windows")']
pkg-fmt = "zip"

[[bin]]
name = "katharsis"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive", "env"] }
glob = "0.3.4"
inquire = "0.9.4"
rss = "2.1.1"
scraper = "0.27.0"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = [
  "fs",
  "io-util",
  "macros",
  "rt-multi-thread",
] }
toml = "1.1.5"
url = { version = "2.5.8", features = ["serde"] }

[dev-dependencies]
tokio-test = "0.4.5"

[lints.clippy]
pedantic = "warn"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage,coverage_nightly)"] }

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
