[graph]
all-features = true

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "MPL-2.0",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
