blank_issues_enabled: false
contact_links:
  - name: Ask a question or discuss a topic
    url: https://github.com/kurosakishigure/katharsis/discussions
    about: Ask questions or discuss with other Katharsis users in discussions.
