name: Report a documentation issue
description: Improvements or additions to documentation.
labels: [ 'documentation' ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us update our docs!
  - type: input
    id: page_link
    attributes:
      label: Page Link
      description: The URL of the page where the document is located.
      placeholder: ex. https://example.com/docs/USE.md
  - type: textarea
    id: documentation_issue
    attributes:
      label: What is the documentation issue?
      description: Improvements or additions to documentation.
    validations:
      required: true
  - type: textarea
    id: any_context
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: false
