name: Audit

on:
  schedule:
    # Runs every Monday.
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  insight:
    name: Insight
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Insight
        uses: arghena/insight@27e7353bf6724e32a813c54a739c5cdfd180ff0d # v0.1.0-canary.57
