name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cargo deny
        uses: EmbarkStudios/cargo-deny-action@v2
