name: CD

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+', 'v[0-9]+.[0-9]+.[0-9]+-canary.[0-9]+']

permissions:
  contents: read

jobs:
  build-dist:
    name: Build for ${{ matrix.job.os }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      # NOTE: Using `cross` for GNU targets to build against an older glibc,
      # keeping the binary compatible with older Linux distros.
      # https://github.com/cross-rs/cross/blob/main/README.md#supported-targets
      matrix:
        job:
          - os: macos-15-intel
            target: x86_64-apple-darwin
            use-cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            use-cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use-cross: false
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            use-cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: true
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            use-cross: true
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            use-cross: true
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
            use-cross: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Rust stable
        shell: bash
        run: |
          if [[ "${{ matrix.job.use-cross }}" == "true" ]]; then
            rustup toolchain install stable --profile minimal --no-self-update --override
          else
            rustup toolchain install stable --profile minimal --no-self-update --override --target ${{ matrix.job.target }}
          fi
      - name: Install cross
        if: ${{ matrix.job.use-cross }}
        uses: taiki-e/install-action@1ed6d7be6168f6c9046541087ff549b6bc581fdf # v2.87.2
        with:
          tool: cross
      - name: Cargo build
        shell: bash
        run: |
          if [[ "${{ matrix.job.use-cross }}" == "true" ]]; then
            cross build --release --locked --target ${{ matrix.job.target }}
          else
            cargo build --release --locked --target ${{ matrix.job.target }}
          fi
      - name: Install binutils for ARM32
        if: ${{ matrix.job.target == 'arm-unknown-linux-gnueabihf' }}
        run: sudo apt update && sudo apt install -y binutils-arm-linux-gnueabihf
      - name: Package final binary
        shell: bash
        env:
          PROJECT_NAME: katharsis
          TARGET: ${{ matrix.job.target }}
        run: ./etc/ci/before_deploy.sh
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist-${{ matrix.job.target }}
          path: |
            katharsis-*-${{ matrix.job.target }}.*
            katharsis*.deb

  create-attestation:
    permissions:
      id-token: write
      attestations: write
      # artifact-metadata: write
      # https://github.com/actions/attest/blob/main/README.md#container-image
    needs: build-dist
    name: Create attestation
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - name: Generate attestation
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: dist/katharsis*

  create-release-note:
    permissions:
      contents: write
    needs: create-attestation
    name: Create release note
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node and pnpm
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          runtime: node@lts
          version: latest
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - name: Generate release note
        # NOTE: The recommended workflow for publishing an immutable release
        # will be to initially create the release as a draft,
        # attach any associated assets, and then publish the draft.
        # https://github.com/orgs/community/discussions/171210#discussioncomment-14237940
        run: |
          if [[ $GITHUB_REF_NAME == *canary* ]]; then
            pnpm dlx changelogithub --prerelease --draft
          else
            pnpm dlx changelogithub --draft
          fi

          gh release upload "$GITHUB_REF_NAME" -- dist/katharsis*
          gh release edit "$GITHUB_REF_NAME" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-to-crates-io:
    permissions:
      id-token: write
      contents: read
    # NOTE: `cargo-binstall` needs the release assets (binaries) to be publicly available.
    needs: create-release-note
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Rust stable
        run: rustup toolchain install stable --profile minimal --no-self-update --override
      - name: Authenticate with crates.io
        id: auth
        uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1.0.5
      - name: Cargo publish
        run: cargo publish --locked
        env:
          CARGO_INCREMENTAL: 0
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  publish-to-winget:
    # NOTE: The action will only work when the release is published (not a draft),
    # because the release assets (binaries) aren't available publicly until the release is published.
    # https://github.com/vedantmgoyal9/winget-releaser/blob/main/README.md#getting-started-
    needs: create-release-note
    name: Publish to WinGet
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: arghena.katharsis
          installers-regex: '-pc-windows-msvc\.zip$'
          # NOTE: New fine-grained PATs aren't supported by the action.
          # https://github.com/vedantmgoyal9/winget-releaser/issues/172
          token: ${{ secrets.BOT_TOKEN }}
