name: CI

on:
  push:
    branches: [ "canary", "[0-9]+-[0-9]+-[0-9]+" ]
  pull_request:
    branches: [ "canary" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fmt
        run: cargo fmt --check --verbose
      - name: clippy
        run: cargo clippy -- -D warnings --verbose
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose

  release:
    name: Release Build and Publish
    #    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest, macos-13 ]
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - name: Add Cross Compilation Targets
        run: |
          rustup target add ${{ matrix.target }}
      - name: Build Release Binary
        run: cargo build --release --target ${{ matrix.target }}
      - name: Archive Binary
        run: |
          mkdir -p dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/katharsis.exe dist/katharsis-${{ matrix.target }}.exe
          else
            cp target/${{ matrix.target }}/release/katharsis dist/katharsis-${{ matrix.target }}
          fi
#      - name: Upload Binary to GitHub Releases
#        uses: softprops/action-gh-release@v1
#        with:
#          files: dist/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
