name: CI

on:
  push:
    branches: [ "canary" ]
  pull_request:
    branches: [ "canary" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fmt
        run: cargo fmt --verbose
      - name: clippy
        run: cargo clippy --verbose
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose
