name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: [canary]
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false
          - os: macos-15-intel
            target: x86_64-apple-darwin
            use-cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            use-cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: false
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            use-cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            use-cross: false
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            use-cross: false
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            use-cross: true
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
            use-cross: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Rust stable
        shell: bash
        run: |
          if [[ "${{ matrix.job.use-cross }}" == "true" ]]; then
            rustup toolchain install stable --profile minimal --no-self-update --override
          else
            rustup toolchain install stable --profile minimal --no-self-update --override --target ${{ matrix.job.target }}
          fi
      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          # NOTE: We need to distinguish the cache when `use-cross` is `true`.
          key: ${{ matrix.job.target }}
          save-if: ${{ github.ref_name == 'canary' }}
      - name: Install cross
        if: ${{ matrix.job.use-cross }}
        uses: taiki-e/install-action@1ed6d7be6168f6c9046541087ff549b6bc581fdf # v2.87.2
        with:
          tool: cross
      - name: Install nextest
        # TODO: Waiting for cross to support nextest.
        # https://github.com/cross-rs/cross/issues/716
        if: ${{ !matrix.job.use-cross }}
        uses: taiki-e/install-action@1ed6d7be6168f6c9046541087ff549b6bc581fdf # v2.87.2
        with:
          tool: cargo-nextest
      - name: Run tests
        shell: bash
        run: |
          if [[ "${{ matrix.job.use-cross }}" == "true" ]]; then
            cross test --locked --target ${{ matrix.job.target }}
          else
            cargo nextest run --locked --target ${{ matrix.job.target }}
          fi
      - name: Run doctests
        # TODO: Waiting for nextest to support doctests.
        # https://github.com/nextest-rs/nextest/issues/16
        if: ${{ !matrix.job.use-cross }}
        run: cargo test --doc --locked --target ${{ matrix.job.target }}

  smoke-tests:
    name: Smoke tests
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Rust stable
        run: rustup toolchain install stable --profile minimal --no-self-update --override
      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          save-if: ${{ github.ref_name == 'canary' }}
      - name: Build for release
        run: cargo build --release --locked --target ${{ matrix.job.target }}
      - name: Run smoke checks
        run: |
          cargo run --release --locked --target ${{ matrix.job.target }} init
          cargo run --release --locked --target ${{ matrix.job.target }}

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Rust stable
        run: rustup toolchain install stable --profile minimal --no-self-update --override
      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          save-if: ${{ github.ref_name == 'canary' }}
      - name: Check documentation
        run: cargo doc --no-deps --document-private-items --locked
        env:
          RUSTDOCFLAGS: -D warnings

  coverage:
    permissions:
      id-token: write
      contents: read
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      # NOTE: Nightly Rust is required for `cargo llvm-cov --doc`.
      # https://github.com/taiki-e/cargo-llvm-cov/issues/2
      # https://nexte.st/docs/integrations/test-coverage/#collecting-coverage-data-from-doctests
      #
      # NOTE: Using `Swatinem/rust-cache` with Nightly Rust is less effective as it will throw away the cache every day.
      # https://github.com/Swatinem/rust-cache/blob/master/README.md#cache-effectiveness
      - name: Install Rust nightly
        run: rustup toolchain install nightly --profile minimal --no-self-update --override
      - name: Install llvm-tools-preview component
        run: rustup component add llvm-tools-preview
      - name: Install llvm-cov
        uses: taiki-e/install-action@1ed6d7be6168f6c9046541087ff549b6bc581fdf # v2.87.2
        with:
          tool: cargo-llvm-cov
      - name: Install nextest
        uses: taiki-e/install-action@1ed6d7be6168f6c9046541087ff549b6bc581fdf # v2.87.2
        with:
          tool: cargo-nextest
      - name: Collect coverage data
        run: |
          cargo llvm-cov --locked --no-report nextest
          cargo llvm-cov --locked --no-report --doc
          cargo llvm-cov report --locked --doctests --lcov --output-path lcov.info
        env:
          CARGO_INCREMENTAL: 0
          RUSTDOCFLAGS: -D warnings
      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          files: lcov.info
