name: Pull Request Security Audit

on:
  pull_request:
    branches: [ 'canary' ]

jobs:
  sg-lint:
    runs-on: ubuntu-latest
    name: Run ast-grep lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: ast-grep lint
        uses: ast-grep/action@latest
